# Use an official Node.js image as the base
FROM node:18

# Set working directory
WORKDIR /usr/src/frontend

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY frontend/ .

# Build the Next.js app
RUN npm run build

# Expose the port for the Next.js app
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "run", "start"]
