version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    container_name: laravel_backend
    volumes:
      - ../backend:/var/www
    ports:
      - "8000:8000"  # Laravel app running on port 8000
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
    container_name: nextjs_frontend
    volumes:
      - ../frontend:/usr/src/app
    ports:
      - "3000:3000"  # Next.js app running on port 3000
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
